---
title: UpKigali
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    reading_time: true
    show_tags: true
    show_categories: true
description: fata gahunda with upkigali
url: http://upkigali.com
markdown: kramdown
future: true
