
# Site settings
title: UpKigali
description: UpKigali is an event marketing website showcasing local events going on or upcoming in Kigali.

url: "http://yourdomain.com"

# Build settings
markdown: kramdown

future: true
