
# Site settings
title: UpKigali
description: UpKigali is an event marketing website showcasing local events going on or upcoming in Kigali.

url: "http://upkigali.com"

# Build settings
markdown: kramdown

future: true

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: true
        # Meta
        show_tags: true
        show_categories: true